// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PruebaBackend;

#nullable disable

namespace PruebaBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241208180724_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PruebaBackend.AutoMarca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AutosMarca");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Sedán",
                            Estado = "Nuevo",
                            Marca = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "SUV",
                            Estado = "Usado",
                            Marca = "Honda"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Camioneta",
                            Estado = "Nuevo",
                            Marca = "Ford"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
