version: '3.4'

services:
  db:
    image: pruebapost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: poro123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=postgres;Username=postgres;Password=poro123
    ports:
      - "5000:80"
    depends_on:
      - db
