using Microsoft.EntityFrameworkCore;

namespace PruebaBackend
{
    public class AppDbContext : DbContext
    {
        public DbSet<AutoMarca> AutosMarca { get; set; } = null!;

        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseNpgsql("Host=localhost;Port=5433;Database=postgres;Username=postgres;Password=poro123");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AutoMarca>(entity =>
            {
                entity.Property(e => e.Id)
                      .UseIdentityColumn(); // Esto asegura que solo 'GENERATED BY DEFAULT AS IDENTITY' sea usado.
            });
           
            modelBuilder.Entity<AutoMarca>().HasData(
                new AutoMarca
                {
                    Id = 1,
                    Descripcion = "Sedán",
                    Marca = "Toyota",
                    Estado = "Nuevo"
                },
                new AutoMarca
                {
                    Id = 2,
                    Descripcion = "SUV",
                    Marca = "Honda",
                    Estado = "Usado"
                },
                new AutoMarca
                {
                    Id = 3,
                    Descripcion = "Camioneta",
                    Marca = "Ford",
                    Estado = "Nuevo"
                }
            );
        }

    }
}
